// Dimension constants for the entire application
export const DIMENSIONS = {
  // Text Element Constants
  TEXT_MIN_WIDTH: 50,
  TEXT_MIN_HEIGHT: 30,
  TEXT_BORDER_WIDTH: 2,
  TEXT_BORDER_RADIUS: 4,
  TEXT_PADDING: 4,
  TEXT_DEFAULT_FONT_SIZE: 32,
  TEXT_COPY_OFFSET: 20,

  // Control Handle Constants
  CONTROL_HANDLE_SIZE: 16,
  CONTROL_HANDLE_RADIUS: 8,
  CONTROL_HANDLE_BORDER: 2,
  CONTROL_HANDLE_OFFSET: -8,
  CONTROL_BUTTON_OFFSET: 40,
  CONTROL_BUTTON_MARGIN: -15,

  // Shadow Constants
  SHADOW_OFFSET_WIDTH: 0,
  SHADOW_OFFSET_HEIGHT: 2,
  SHADOW_OPACITY: 0.3,
  SHADOW_RADIUS: 3,
  SHADOW_ELEVATION: 5,
  TEXT_SHADOW_OFFSET: {width: 1, height: 1},
  TEXT_SHADOW_RADIUS: 2,

  // Bottom Sheet Constants
  BOTTOM_SHEET_BORDER_RADIUS: 20,
  BOTTOM_SHEET_HANDLE_WIDTH: 40,
  BOTTOM_SHEET_HANDLE_HEIGHT: 4,
  BOTTOM_SHEET_PADDING_HORIZONTAL: 20,
  BOTTOM_SHEET_PADDING_VERTICAL: 10,
  BOTTOM_SHEET_MARGIN_BOTTOM: 20,

  // Button Constants
  BUTTON_PADDING_VERTICAL: 16,
  BUTTON_PADDING_HORIZONTAL: 12,
  BUTTON_BORDER_RADIUS: 12,
  BUTTON_MARGIN_BOTTOM: 12,
  BUTTON_BORDER_WIDTH: 1,
  BUTTON_ICON_SIZE: 24,
  BUTTON_ICON_MARGIN: 16,

  // Font Sizes
  FONT_SIZE_TITLE: 20,
  FONT_SIZE_BODY: 16,
  FONT_SIZE_SMALL: 14,

  // Canvas Constants
  CANVAS_BORDER_WIDTH: 1,
  CANVAS_SCREEN_WIDTH_FACTOR: 0.9,
  CANVAS_SCREEN_HEIGHT_FACTOR: 0.7,

  // Template Constants
  TEMPLATE_GRID_COLUMNS: 2,
  TEMPLATE_GRID_SPACING: 60,
  TEMPLATE_DEFAULT_SIZE: 400,

  // Scale Constants
  MIN_SCALE: 0.5,
  MAX_SCALE: 3,
  DEFAULT_SCALE: 1,

  // Animation Constants
  GESTURE_ROTATION_DIVISOR: 100,
  GESTURE_SCALE_DIVISOR: 20,
  GESTURE_SCALE_MULTIPLIER: 0.15,

  // Positioning Constants
  DEFAULT_POSITION: 0,
  CORNER_OFFSET: -5,

  // Input Constants
  INPUT_MULTILINE_HEIGHT: 100,
  COLOR_PICKER_ITEM_SIZE: 40,
  COLOR_PICKER_BORDER_RADIUS: 20,
  COLOR_PICKER_BORDER_WIDTH: 2,

  // Active Opacity
  TOUCH_ACTIVE_OPACITY: 0.7,
  BUTTON_ACTIVE_OPACITY: 0.8,
} as const;
